# Generated by Django 3.2.18 on 2023-08-08 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(default='', max_length=300)),
                ('totalsem', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='department_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='election_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionname', models.CharField(default='', max_length=100)),
                ('electiondeclareddate', models.CharField(default='', max_length=10)),
                ('electiondate', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subadmin_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subadminname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneno', models.CharField(default='', max_length=10)),
                ('photo', models.FileField(default='', upload_to='')),
                ('LOGIN', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.login_tab')),
            ],
        ),
        migrations.CreateModel(
            name='student_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('photo', models.FileField(default='', upload_to='')),
                ('housename', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('semster', models.CharField(default='', max_length=100)),
                ('COURSE', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.course_tab')),
                ('LOGIN', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.login_tab')),
            ],
        ),
        migrations.CreateModel(
            name='staff_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=20)),
                ('photo', models.FileField(default='', upload_to='')),
                ('housename', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('DEPARTMENT', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.department_tab')),
                ('LOGIN', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.login_tab')),
            ],
        ),
        migrations.CreateModel(
            name='nominees_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submiteddate', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('ELECTION', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.election_tab')),
                ('STUDENT', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.student_tab')),
            ],
        ),
        migrations.CreateModel(
            name='electioncoordinator_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ELECTION', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.election_tab')),
                ('STAFF', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.staff_tab')),
            ],
        ),
        migrations.AddField(
            model_name='course_tab',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.department_tab'),
        ),
        migrations.CreateModel(
            name='complaint_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=10)),
                ('reply', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=50)),
                ('USER', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.student_tab')),
            ],
        ),
    ]
