# Generated by Django 3.2.18 on 2023-08-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0002_remove_staff_tab_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_tab',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Evoting_app.login_tab'),
        ),
    ]
