# Generated by Django 3.2.18 on 2023-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0004_alter_login_tab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tab',
            name='photo',
            field=models.FileField(default='', max_length=500, upload_to=''),
        ),
    ]
