# Generated by Django 3.2.18 on 2023-09-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0005_alter_student_tab_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tab',
            name='photo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
